### ISSUE TITLE
Add Help Beacon

### ISSUE THREAD

**Issue by agstephens** [cedadev/pyramid-phoenix#11]
@gap736uk : please send @antony-wilson the required content for adding the Help beacon to the new WPS UI.

**Comment by gap736uk** [comment]
Code snippet to use (places just before the </body> tag:

<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', '0151e3db-1a06-48d6-a030-d1c605683be9')</script>


this should be in the template to that it will appear on all pages in the new WPS system.

**Comment by antony-wilson** [comment]
Done https://github.com/cedadev/pyramid-phoenix/commit/7d65b19651be862472fe375e12c9a174473efd60

**Comment by agstephens** [comment]
Now deployed. 
@gap736uk: please test on the production site and close this issue if all good.
