### ISSUE TITLE
Hide user profile page in Phoenix (and link to it from top-right corner)

### ISSUE THREAD

**Issue by agstephens** [cedadev/pyramid-phoenix#23]

**Comment by antony-wilson** [comment]
Changes have been made for where user management is handled outside of Phoenix.

A new variable has been introduced, `local-user-management`, which can
be set in the `custom.cfg`, e.g. `local-user-management = false`. By
default the value is `true` and the current behaviour remains unchanged.

When set to `false` then a number of end-points will not be found:
- people
- people/profile/{userid}/{tab}
- people/delete/{userid}

These items will also be removed from the navbar
