### ISSUE TITLE
Get phoenix to read metalink document to provide direct download links to NC files

### ISSUE THREAD

**Issue by agstephens** [cedadev/pyramid-phoenix#26]
Extend phoenix so that it will read the metalink file (`input.meta4`) and parse the output file paths (e.g. netcdf/csv). Then display these at the top of the listing of outputs.

Note that the metalink file can also still be linked but it can be listed last.

**Comment by antony-wilson** [comment]
The files get sorted and displayed in alphabetic order

**Comment by antony-wilson** [comment]
The outputs from the metadata links are now extracted and then prepended to the list of other outputs after that list has been sorted.

**Comment by agstephens** [comment]
This is working perfectly - so closing this one.
