### ISSUE TITLE
Add time range selector widget to phoenix

### ISSUE THREAD

**Issue by agstephens** [cedadev/pyramid-phoenix#3]
We need a nice widget to provide a time range input.

**Comment by antony-wilson** [comment]
@agstephens Somehow the server has to tell the client it wants a range. The input can be one of:

- BoundingBoxData
- ComplexData
- Literal

It is possible to define the `Literal` as one of:

- float
- boolean
- integer
- string
- positiveInteger
- anyURI
- time
- date
- dateTime
- scale
- angle
- nonNegativeInteger

An ideal solution would be if there was a literal type of `range`.
I'll take a look at `ComplexData` and see if we can use that

**Comment by agstephens** [comment]
@antony-wilson: the problem with Complex Inputs is that that they are typically not represented as simple strings. My suggested solution to this problem is to provide the range as two inputs, e.g.:

```
            LiteralInput('start', 'Start Date Time',
                         abstract='The first date/time for which to search for operating weather stations.',
                         data_type='dateTime',
                         default='2017-10-01T12:00:00Z'),
            LiteralInput('end', 'End Date Time',
                         abstract='The last date/time for which to search for operating weather stations.',
                         data_type='dateTime',
                         default='2018-02-25T12:00:00Z'),
```

@cehbrecht - do you have thoughts on the best approach here?

**Comment by cehbrecht** [comment]
@antony-wilson there is an example for a literal value using a range in emu:
https://github.com/bird-house/emu/blob/f8dc7a5cfdcf6cea125eb165250ee5a020c8432b/emu/processes/wps_inout.py#L68

But it is using `int` ... not `string` or `datetime`. Not sure if it works for other literal types. See also the links provided:
* https://docs.opengeospatial.org/is/14-065/14-065.html#98
* https://pywps.readthedocs.io/en/master/api.html#pywps.inout.literaltypes.AllowedValue

**Comment by cehbrecht** [comment]
An alternative would be to use two literal inputs `start` and `end` as Ag has show above.

In roocs we use one time string: `start/end`:
https://github.com/roocs/rook/blob/2cb83c7161355f7b519799086ed025ec4300bc5c/rook/processes/wps_subset.py#L24

**Comment by antony-wilson** [comment]
So using the roocs example, in Phoenix I would have to check for data type of string and then use one of the other fields to give the string special meaning, ie if name=time use date range widget

**Comment by cehbrecht** [comment]
> So using the roocs example, in Phoenix I would have to check for data type of string and then use one of the other fields to give the string special meaning, ie if name=time use date range widget

When using a string you can identify it by the name ... might work for now but not a general solution. You could also use `metadata` to give information about the type. I have no good example ... but something like this:
https://github.com/bird-house/emu/blob/f8dc7a5cfdcf6cea125eb165250ee5a020c8432b/emu/processes/wps_esgf.py#L25

**Comment by antony-wilson** [comment]
How about something like

```
            LiteralInput('dateRange', 'Date Range',
                         abstract='The years for which to search for operating weather stations.',
                         data_type='integer',
                         default='2017-10-01T12:00:00Z')
                         min_occurs=2,
                         max_occurs=2,
                         allowed_values=[
                             AllowedValue(minval=1900, maxval=2020, spacing=10)
                         ],
```

**Comment by antony-wilson** [comment]
@cehbrecht I added the above` LiteralInput` with `AllowedValue(minval=1900, maxval=2020, spacing=10)` as an extra input to the in-out process in Emu. 
This is a section of the XML that Phoenix get as part of the `DescribeProcess` request
```
			<Input minOccurs="2" maxOccurs="2">
				<ows:Identifier>dateRange</ows:Identifier>
				<ows:Title>Date Range</ows:Title>
				<ows:Abstract>The years for which to search for operating weather
					stations.</ows:Abstract>
				<LiteralData>
					<ows:DataType
						ows:reference="http://www.w3.org/TR/xmlschema-2/#integer">integer</ows:DataType>
					<ows:AllowedValues>
						<ows:Range ows:rangeClosure="closed">
							<ows:MinimumValue>1900</ows:MinimumValue>
							<ows:MaximumValue>2020</ows:MaximumValue>
							<ows:Spacing>10</ows:Spacing>
						</ows:Range>
					</ows:AllowedValues>
				</LiteralData>
			</Input>
```
So far so good
However the `dataInputs.allowedValues` for this input is an empty list.

I think this may be a bug in WebProcessingService.describeprocess() from  owslib.wps

**Comment by cehbrecht** [comment]
> So using the roocs example, in Phoenix I would have to check for data type of string and then use one of the other fields to give the string special meaning, ie if name=time use date range widget

I suppose you want to make a new widget for the date range. I think using the roocs approach with a simple string `start-year/end-year` might be simplest. You won't have validation on the WPS side ... but you can validate the input  on the client side (colander validator?).

**Comment by cehbrecht** [comment]
> So far so good
> However the `dataInputs.allowedValues` for this input is an empty list.
> 
> I think this may be a bug in WebProcessingService.describeprocess() from owslib.wps

could be that the allowed value ranges are not implement in `OWSLib`.

**Comment by antony-wilson** [comment]
@cehbrecht I was just looking at the inout process from emu for inspiration and when you load the form for this process in Phoenix there is a javascript error
```
Uncaught TypeError: $(...).select2 is not a function
    <anonymous> https://192.168.128.200:5043/processes/execute?wps=593f8ec8e6324eb49016471f261db97a&process=inout:475
    processCallbacks https://192.168.128.200:5043/static-deform/scripts/deform.js:37
    jQuery 2
    processCallbacks https://192.168.128.200:5043/static-deform/scripts/deform.js:34
    load https://192.168.128.200:5043/static-deform/scripts/deform.js:28
    jQuery 11
    load https://192.168.128.200:5043/static-deform/scripts/deform.js:26
    <anonymous> https://192.168.128.200:5043/static-deform/scripts/deform.js:8
    jQuery 13
execute:475:21
```

This can be seen https://bovec.dkrz.de/processes/execute?wps=emu&process=inout

**Comment by antony-wilson** [comment]
Two new widgets with make use of `jQRangeSlider` have been added:

- a numeric range slider
- a date range slider

Currently they are specialisations of `LiteralInput` `data_type='string'`

If a string input has an id starting with `range_slider` then a numeric range slider is created. If the input has defaults in the format of `'nnnn|nnnn'` then tases are used to set the range of the slider

If a string input has an id starting with `date_slider` then a date range slider is created. If the input has defaults in the format of `'yyyy/mm/dd|yyyy/mm/dd'` then tases are used to set the range of the slider
