### ISSUE TITLE
Add bounding box widget to phoenix

### ISSUE THREAD

**Issue by agstephens** [cedadev/pyramid-phoenix#4]
We need to build a bounding box widget for phoenix.

**Comment by agstephens** [comment]
This info might be useful:

https://github.com/geopython/pywps/issues/404

**Comment by antony-wilson** [comment]
box code added in commit 70146f58196f381ffbc2a1bc589b075147e7481f

**Comment by antony-wilson** [comment]
We now have a working map widget.

The projection, `EPSG:4326`, covers 90 degrees north to 90 degrees south. This results in a map that does not look to good as you move away from the equator.

A future enhancement is to add a check to see if the default bounding box is within 85 degrees north to 85 degrees south, in which case the projection `EPSG:3857` can be used. This will require the additional complexity of converting units to and from lat and long for the input fields displayed to the user and the hidden input values.
